### PR TITLE
Mrkaiser patch 1

### PR DESCRIPTION
**Pull request by mrkaiser**
Modification of test and updated version of pip in the version.csv

### CODE REVIEW

**Comment by mrkaiser** [comment]
Finally realized that you use both the MD5 and the SHA1. Curious as to why, but I guess better safe than sorry when downloading and checking for corrupt packages.

**Comment by mrkaiser** [comment]
I believe wheel (or whatever brings it in as a dep... setuptools?) needs updating to support Python 3.5. Will find the issue and open a separate pull request.

**Comment by brainsik** [comment]
Hello. It's best to upgrade the dependencies to match what the installed version of virtualenv uses. I'm currently waiting for virtualenv v14.0.x (which uses pip 8.x) to stabilize. When it gets to a happy place I'll upgrade all the related dependencies.

Out of curiosity, what issue are you hoping to solve for yourself with the upgraded pip?

**Comment by mrkaiser** [comment]
Just trying to squelch some annoying error messages. When I try to do the
upgrade in-place it complains that the base pip version is different and it
aborts the installation (I don't have the exact wording right now... I can
post it when I get home).

**Comment by brainsik** [comment]
Versions have been bumped in a different PR. Upgrade for the latest versions. Thanks for submitting!

**Pull request closed without merging**
