### PR TITLE
Add script to automatically update dependencies

### PR DESCRIPTION
**Pull request by mattrobenolt**
@brainsik Do you have an opinion about doing this? :+1: :-1: This will make it a bit easier to keep up to date.

### CODE REVIEW

**Comment by brainsik** [comment]
Sorry, just saw this. I was away for a few months.

So, this looks like it's using the latest version of things, but what we want to do is match the versions to whatever is shipping with the version of virtualenv we include. You can see what versions ship with virtualenv by looking at [the virtualenv changelog](https://virtualenv.pypa.io/en/latest/changes/). Does that make sense?

**Comment by mattrobenolt** [comment]
@brainsik The script queries `virtualenvwrapper` and takes the versions associated with that. So from my understanding and how I've been bumping versions, this has worked.

**Comment by mattrobenolt** [comment]
Also, this was first bump with this script: https://github.com/brainsik/virtualenv-burrito/commit/ead9dae393f77126c4a5eb2a5f8eb2a58e04363b

**Comment by mattrobenolt** [comment]
Specifically, this is the relevant pieces: https://github.com/brainsik/virtualenv-burrito/blob/master/update_dependencies.py#L161-L180

**Pull request merged**
