### PR TITLE
Updated setup-tools,pip,virtualenv and virtualenv-wrapper

### PR DESCRIPTION
**Pull request by silentninja**

### CODE REVIEW

**Comment by brainsik** [comment]
@silentninja Did you test this out with a brand new install using these versions? In the past, newer pip has caused problems installing package dependencies.

**Comment by brainsik** [comment]
@silentninja Also, upgrading pip here won't affect the version that's installed into a virtualenv (which is why I believe you are doing this). For that, it's based on the version that ships with the virtualenv package.

**Comment by brainsik** [comment]
CC @mmukesh95

**Comment by silentninja** [comment]
I tested it out using the latest versions and it worked perfectly fine.The latest virtualenv(13.0.3) package is using pip(7.0.3),So i hope the latest pip version wont be causing problems.
https://pypi.python.org/pypi/virtualenv

**Comment by egrim** [comment]
:+1:

**Comment by brainsik** [comment]
Just tested it and the latest pip suffers the same issue that's been going on for a while. On Mac, there is a failure when pip installs the `six` package required by virtualenvwrapper. At the end, you are left with a broken installation.

Looking at the latest pip to see if there are some new command-line flags that might help me work around the issue.

All that said, the version of pip installed by virtualenv-burrito does not affect the version that's installed into new virtualenvs. That's handled by the virtualenv package itself. Perhaps all you want is for that package to get bumped?

**Comment by brainsik** [comment]
Figured it out in 3c27d8815acfef8acfc46c94170a5d0fa3c3a99b.

All packages are updated and a `virtualenv-burrito upgrade` should update them all.

**Comment by silentninja** [comment]
I wanted to upgrade all the package to the latest.Thanks for the update

**Pull request closed without merging**
